### ISSUE TITLE
Under which license is the code licensed?

### ISSUE THREAD

**Issue by traversaro** [BerkeleyAutomation/ipc-graspsim#1]
First of all, thanks a lot for the amazing work and for distributing the reference implementation as open source!

I was wondering under which license the code is distributed, as I could not find any indication in the repo. See https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository or https://choosealicense.com/ for more details on open source software licenses.

**Comment by chungmin99** [comment]
Thanks for pointing this out - updated with license! :)

**Comment by traversaro** [comment]
Great, thanks!
